version: 0.2

phases:
   
    build:
        commands:
            - cd ./IssueTracker
            - dotnet publish -c release
            
artifacts:
  files:
    - IssueTracker/IssueTracker/build_output/*