version: 0.2

phases:
   
    build:
        commands:
            - dotnet publish IssueTracker/IssueTracker.csproj -c release -o ./output 
            
artifacts:
  files:
    - ./output/**/*
    - appspec.yml