version: 0.2

phases:
   
    build:
        commands:
            - cd ./IssueTracker
            - dotnet restore
            - dotnet publish IssueTracker/IssueTracker.csproj -c Release -o ../output
            
artifacts:
  files:
    - '**/*'
  base-directory: ./IssueTracker/output