version: 0.2

phases:
   
    build:
        commands:
            - cd ./IssueTracker
            - dotnet publish -c release -o ./build_output ./IssueTracker/IssueTracker/IssueTracker.csproj
            
artifacts:
  files:
    - IssueTracker/IssueTracker/build_output/*