version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    
    build:
        commands:
            - dotnet publish -c release -o ./build_output ./IssueTracker/IssueTracker/IssueTracker.csproj
            
artifacts:
  files:
    - IssueTracker/IssueTracker/build_output/*