version: 0.2

phases:
   
    build:
        commands:
            - cd ./IssueTracker
            - dotnet publish -c release
            
artifacts:
  files:
    - src\IssueTracker\bin\release\netcoreapp3.1\publish\*